{
 "title": "Week2 Project Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Alerts",
   "type": "alertlist",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "ALERTS{alertstate!=\"pending\"}",
     "legendFormat": "{{alertname}}"
    }
   ]
  },
  {
   "title": "KubePodNotReady",
   "type": "stat",
   "description": "Pod {{ $labels.namespace }}/{{ $labels.pod }} has been in a non-ready state for longer than 5 minutes.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace, pod) (max by (namespace, pod) (kube_pod_status_phase{job=\"kubernetes-service-endpoints\",namespace=~\".*\",phase=~\"Pending|Unknown\"}) * on (namespace, pod) group_left (owner_kind) topk by (namespace, pod) (1, max by (namespace, pod, owner_kind) (kube_pod_owner{owner_kind!=\"Job\"}))) > 0"
    }
   ]
  },
  {
   "title": "Available Node Memory",
   "type": "gauge",
   "description": "This is the gauge counter for Node memory which is available. If it is <85%, it's low. \n",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Number of Instances Down",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 11, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"kubernetes-nodes\"} == 0",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}